import scrapy

class FlipkartItem(scrapy.Item):
    product_id = scrapy.Field()
    product_name = scrapy.Field()
    brand = scrapy.Field()
    category = scrapy.Field()
    price = scrapy.Field()
    original_price = scrapy.Field()
    discount = scrapy.Field()
    description = scrapy.Field()
    product_images = scrapy.Field()
    product_rating = scrapy.Field()
    review_count = scrapy.Field()
    availability = scrapy.Field()
    sku = scrapy.Field()
    shipping_info = scrapy.Field()
    size_color_options = scrapy.Field()
    product_url = scrapy.Field()
    product_dimensions = scrapy.Field()
    weight = scrapy.Field()
    material = scrapy.Field()
    customer_questions = scrapy.Field()
    seller_info = scrapy.Field()
    return_policy = scrapy.Field()
    warranty = scrapy.Field()
