
class FlipkartSelectors:
    PRODUCT_ID = '::attr(data-id)'
    PRODUCT_NAME = 'a.IRpwTa::text'
    BRAND = 'div._2WkVRV::text'
    CATEGORY = 'a._2whKao::text'
    PRICE = 'div._30jeq3::text'
    ORIGINAL_PRICE = 'div._3I9_wc::text'
    DISCOUNT = 'div._3Ay6Sb span::text'
    DESCRIPTION = 'div._1mXcCf::text'
    PRODUCT_IMAGES = 'img._396cs4::attr(src)'
    PRODUCT_RATING = 'div._3LWZlK::text'
    REVIEW_COUNT = 'span._2_R_DZ::text'
    AVAILABILITY = 'div._16FRp0::text'
    SKU = '::attr(data-sku)'
    SHIPPING_INFO = 'div._2pqhhf::text'
    SIZE_COLOR_OPTIONS = 'a._1fGeJ5::text'
    PRODUCT_URL = 'a::attr(href)'
    PRODUCT_DIMENSIONS = 'div._1UhVsV li::text'
    WEIGHT = 'div._1UhVsV li::text'
    MATERIAL = 'div._1UhVsV li::text'
    CUSTOMER_QUESTIONS = 'div._1UhVsV li::text'
    SELLER_INFO = 'div._3HGjxn::text'
    RETURN_POLICY = 'div._3XINqE::text'
    WARRANTY = 'div._3XINqE::text'
