class ScreenerSelectors:
    SYMBOL = 'td[data-column-name="symbol"]::text'
    COMPANY_NAME = 'td[data-column-name="company"]::text'
    MARKET_CAP = 'td[data-column-name="market_cap"]::text'
    PE_RATIO = 'td[data-column-name="pe"]::text'
    PRICE = 'td[data-column-name="price"]::text'
    VOLUME = 'td[data-column-name="volume"]::text'
    SECTOR = 'td[data-column-name="sector"]::text'
    INDUSTRY = 'td[data-column-name="industry"]::text'
    DIVIDEND_YIELD = 'td[data-column-name="dividend_yield"]::text'
    EPS = 'td[data-column-name="eps"]::text'
    BETA = 'td[data-column-name="beta"]::text'
    HIGH_52_WEEK = 'td[data-column-name="high_52week"]::text'
    LOW_52_WEEK = 'td[data-column-name="low_52week"]::text'
    MOVING_AVG_50D = 'td[data-column-name="sma50"]::text'
    MOVING_AVG_200D = 'td[data-column-name="sma200"]::text'
    RELATIVE_VOLUME = 'td[data-column-name="rel_volume"]::text'
    CHANGE_PERCENT = 'td[data-column-name="change_percent"]::text'
