class ScreenerInSelectors:
    SYMBOL = 'td.text-right a::text'
    COMPANY_NAME = 'td.name a::text'
    MARKET_CAP = 'td[data-sort-key="market_cap"]::text'
    CURRENT_PRICE = 'td[data-sort-key="current_price"]::text'
    HIGH_PRICE = 'td[data-sort-key="high_price"]::text'
    LOW_PRICE = 'td[data-sort-key="low_price"]::text'
    PE_RATIO = 'td[data-sort-key="pe"]::text'
    BOOK_VALUE = 'td[data-sort-key="book_value"]::text'
    DIVIDEND_YIELD = 'td[data-sort-key="dividend_yield"]::text'
    ROCE = 'td[data-sort-key="roce"]::text'
    ROE = 'td[data-sort-key="roe"]::text'
    FACE_VALUE = 'td[data-sort-key="face_value"]::text'
    SECTOR = 'td[data-sort-key="sector"]::text'
    PROFIT_GROWTH = 'td[data-sort-key="profit_growth"]::text'
    SALES_GROWTH = 'td[data-sort-key="sales_growth"]::text'
    PROMOTER_HOLDING = 'td[data-sort-key="promoter_holding"]::text'
    DEBT_TO_EQUITY = 'td[data-sort-key="debt_to_equity"]::text'
    WORKING_CAPITAL = 'td[data-sort-key="working_capital"]::text'
